name: feat
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-15.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  horizontal_picker: ^1.2.0
  percent_indicator: ^4.2.3
  toggle_switch: ^2.1.0
  fl_chart: ^0.66.1
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  assets:
    - assets/
  uses-material-design: true
